project:
  type: website

website:
  title: "My Space"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Aman-Govind
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css



