project:
  type: website
  output-dir: docs 

website:
  title: "My Works"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Aman-Govind
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css



